### ISSUE TITLE
Keyboard covers navigation buttons at some input fields.

### ISSUE THREAD

**Issue by dleunig** [DeFiChain-Wizard/defichain-wizard-frontend#5]
The keyboard covers the navigation buttons at some input fields. The keyboard should disappear when clicking outside an input field.

**Comment by dleunig** [comment]
There are some other screens where the problem needs to be fixed. The keyboard should close for all input fields when clicking outside. On the compounding screen, the user cannot continue while the keyboard is open e.g.

**Comment by stephanmueller-nspagency** [comment]
> 

This seems to be a problem on IOS only. I may have a solution for this in place in the developement branch. But I would need confirmation that it works on IOS. It's the TouchableWithoutFeedback component in this [commit](https://github.com/DeFiChain-Wizard/defichain-wizard-frontend/commit/b1771d02c71a87777ccc388bdf8b48bc9164b934).

**Comment by stephanmueller-nspagency** [comment]
Should be fixed with #11
